apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: devops-api-wrapper
  title: On demand environments
  description: Temporary environment in stage k8s cluster
spec:
  owner: devops
  type: service

  parameters:
    - title: Request
      required:
        - envDb
        - imageTag
      properties:
        envName:
          title: Environment Name
          type: string
        envDb:
          title: Env DB
          type: string
          enum:
            - db-local
            - rds
        oneImageTag:
          title: One Image Tag
          type: boolean
          default: true
        imageTag:
          title: Image Tag
          type: string
          default: 1.74.0-release.9e9887f587
        deploymentName:
          title: Deployment name
          type: string
          enum:
            - saas
            - single-tenant
            - on-prem
        chartSource:
          title: Chart Source
          type: string
          enum:
            - helm-repo
            - github-branch
          default: github-branch
        githubBranch:
          title: Github branch
          type: string
          default: main
        pathToChartFolder:
          title: Path to chart folder
          type: string
          default: chart
        ttl:
          title: TTL
          type: string
          enum:
            - 1h
            - 2h
            - 4h
            - 8h
        valuesYaml:
          title: values.yaml
          type: string
          ui:widget: textarea
          ui:options:
            rows: 15
          default: |
            deployments:
              artifacts:
                image:
                  repository: yoni/artifacts-internal
                  tag: 1.74.0-release.9e9887f587

  steps:
    - id: call-devops-api
      name: On demand env
      action: devops:call
      input:
        envDb: ${{ parameters.envDb }}
        oneImageTag: ${{ parameters.oneImageTag }}
        imageTag: ${{ parameters.imageTag }}
        deploymentName: ${{ parameters.deploymentName }}
        chartSource: ${{ parameters.chartSource }}
        githubBranch: ${{ parameters.githubBranch }}
        pathToChartFolder: ${{ parameters.pathToChartFolder }}
        ttl: ${{ parameters.ttl }}
        valuesYaml: ${{ parameters.valuesYaml }}

  output:
    text:
      - title: Result
        content: |
          DevOps request submitted successfully.
