apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: devops-api-wrapper
  title: DevOps Self-Service
  description: Call internal DevOps API from Backstage
spec:
  owner: devops
  type: service

  parameters:
    - title: Request
      required:
        - action
        - environment
      properties:
        envDb:
          title: Env DB
          type: string
          enum:
            - db-local
            - rds
        oneImageTag:
          title: One Image Tag
          type: boolean
          default: true
        imageTag:
          title: Image Tag
          type: string
        deploymentName:
          title: Deployment name
          type: string
          enum:
            - saas
            - single-tenant
            - on-prem
        chartSource:
          title: Chart Source
          type: string
          enum:
            - helm-repo
            - github-branch
        githubBranch:
          title: Github branch
          type: string
          default: main
        pathToChartFolser:
          title: Path to chart folder
          type: string
          default: chart
        ttl:
          title: TTL
          type: string
          enum:
            - 1h
            - 2h
            - 4h
            - 8h

  steps:
    - id: call-devops-api
      name: Call DevOps API
      action: devops:call
      input:
        action: ${{ parameters.action }}
        environment: ${{ parameters.environment }}
        serviceName: ${{ parameters.serviceName }}

  output:
    text:
      - title: Result
        content: |
          DevOps request submitted successfully.
